name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
          APP_ENV: test
          DATABASE_URL="mysql://usrcine:pwdcine@127.0.0.1:3306/cinescope?serverVersion=8.0"
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: isa
          MYSQL_DATABASE: cinescope_test
          MYSQL_USER: usrcine
          MYSQL_PASSWORD: pwdcine
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -pisa"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=30

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, pdo_mysql, xml, zip
          coverage: none

      - run: composer install --no-interaction --prefer-dist

      - name: DB + migrations
        
        run: |
         
          php bin/console doctrine:migrations:migrate -n

      - name: PHPUnit
       
        run: php bin/phpunit
